problem.name=sod
output.interval=0.01
runtime.stop_time=0.1
gravity.enabled=off
mesh.level.maximum=1
runtime.disable_diagnostics=on
#mesh.boundary.reflecting=on
#restart.filename=X.248.silo
#mesh.unigrid=1
