problem.name=sod
output.interval=0.02
runtime.stop_time=0.021
gravity.enabled=off
mesh.level.maximum=3
runtime.disable_diagnostics=on
mesh.scale=0.5
#mesh.boundary.reflecting=on
#restart.filename=X.248.silo
#mesh.unigrid=1
