problem.name=rotating_star
gravity.opening_angle=0.34
mesh.scale=2.033333333333
output.interval=0.5
runtime.stop_time=100
mesh.level.maximum=2
problem.input_file=rotating_star.bin
hydro.species.count=5
mesh.amr.boundary_order=1
runtime.disable_diagnostics=off
problem.rotating_star.center_x=0.033333333
#restart.filename=restart.silo
output.silo.groups=8
mesh.unigrid=on
gravity.angular_momentum_correction=on
