problem=radiation_gaussian_pulse

hydro=off
gravity=off
radiation=on

n_species=1
atomic_mass=1
atomic_number=1

periodic=1
max_level=3

code_to_g=1
code_to_cm=1
code_to_s=1


kappa0=0
kappa_rho_exp=0
kappa_T_exp=0

sigma_rho_exp=0
sigma_T_exp=0


# sigma0 * xscale^2 = constant * rad_diff_t0
# sigma * xscale >= 1e4
xscale=1e8
sigma0=1e-4
rad_diff_t0=1
rad_diff_Er0=1

stop_time=1e-1
odt=1e-3
hard_dt=2e-4


