#!groovy

pipeline {
    agent any

    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: "21",
                numToKeepStr: "50",
                artifactDaysToKeepStr: "21",
                artifactNumToKeepStr: "50"
            )
        )
    }
    stages {
        stage('checkout') {
            steps {
                dir('octotiger') {
                    checkout scm
                    echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                    sh '''
                    #!/bin/bash -l
                    cd ..
                    #rm -rf octo-buildscripts/src/octotiger
                    rm -rf octo-buildscripts #remove line for dependency caching
                    if [[ -d "octo-buildscripts" ]]
                    then
                        cd octo-buildscripts
                        git reset --hard # reset griddim modification in case of unclean directory
                        git pull
                        rm -rf build/octotiger
                    else
                        git clone https://github.com/diehlpk/PowerTiger.git octo-buildscripts
                        cd octo-buildscripts
                        git checkout clang_build
                        mkdir src
                    fi

                    cd ..
                    pwd
                    cp -r octotiger octo-buildscripts/src/octotiger
                    '''
                }
            }
        }
        stage('build') {
            matrix {
                axes {
                    axis {
                        name 'compiler_config'
                        values 'with-CC'
                    }
                    axis {
                         name 'build_type'
                         values 'Release'
                    }
                }
                stages {
                    stage('build') {
                        steps {
                            dir('octo-buildscripts') {
                                sh '''
                                #!/bin/bash -l
                                src/octotiger/.jenkins/lsu/entry.sh
                                '''
                            }
                        }
                    }
                }
            }
        }
    }
}
