#!groovy

void setBuildStatus(String message, String state) {
  step([
      $class: "GitHubCommitStatusSetter",
      reposSource: [$class: "ManuallyEnteredRepositorySource", url: "https://github.com/STEllAR-GROUP/octotiger"],
      contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "ci/jenkins/build-status"],
      errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
      statusResultSource: [ $class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]] ]
  ]);
}

pipeline {
    agent { label 'argon-fs' }

    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: "21",
                numToKeepStr: "50",
                artifactDaysToKeepStr: "21",
                artifactNumToKeepStr: "50"
            )
        )
    }
    stages {
        stage('checkout') {
            steps {
                dir('octotiger') {
                    sh '''
                    echo "Git commit ${GIT_COMMIT} ?"
                    srun -p knl -N 1 -n 1 -t 00:05:00 bash -c "cd /scratch && \
                    mkdir -p jenkins/octotiger && cd jenkins/octotiger && \
                    git clone https://github.com/STEllAR-GROUP/octotiger.git && \
                    cd octotiger && git submodule update --init --recursive && git checkout ${GIT_COMMIT} && cd - && \
                    git checkout https://github.com/STEllAR-GROUP/OctoTigerBuildChain && cd OctoTigerBuildChain/ && \
                    git checkout clang_build && mkdir src && cp -r ../octotiger src/octotiger"
                    '''
                }
            }
        }
    }
}
