function(download_test_reference test_name url dest)
  message(STATUS "Downloading reference SILO file for ${test_name}")
  if(NOT EXISTS ${dest})
    file(DOWNLOAD ${url} ${dest})
  endif()
  message(STATUS "Downloading reference SILO file for ${test_name} -- Success")
endfunction()