problem.name=star
hydro.eos=ipr
runtime.stop_time=90
gravity.opening_angle=0.35
hydro.ipr.newton_max_iterations=75
hydro.ipr.newton_tolerance=1e-12
hydro.ipr.test=on
#mesh.unigrid=on
mesh.scale=100
problem.star.maximum_radius=50
problem.star.alpha=3.024
problem.star.radial_step=0.1953125
problem.star.central_density=0.025
units.grams=1.99e+33
problem.star.external_density=1.7e-14
problem.star.external_gas_energy=3.28e-14
units.centimeters=6.96e+10
mesh.level.maximum=4
hydro.species.atomic_number=1.38
hydro.species.atomic_mass=2.13
output.interval=5.0
hydro.species.count=1
hydro.density_floor=1.7e-14
hydro.entropy_floor=5.36e-09
hydro.ipr.internal_energy_floor=3.28e-14
problem.star.polytropic_index=4.1
hydro.contact_discontinuity_detection=off

runtime.stop_step=10
