problem.name=rotating_star
radiation.enabled=off
#gravity.enabled=off
gravity.opening_angle=0.3334
mesh.scale=2.0
output.interval=0.25
runtime.stop_time=1
mesh.level.maximum=2
problem.input_file=rotating_star.bin
hydro.species.count=5
mesh.amr.boundary_order=1
#output.silo.offset_x=-3
runtime.disable_diagnostics=off
#output.rewrite_silo=on
#problem.rotating_star.center_x=0.375
#problem.rotating_star.amr=true
#runtime.stop_step=1
#restart.filename=restart.silo
output.silo.groups=1
#mesh.omega_z=5.155533e-01
mesh.unigrid=on
